## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []

## @section elastiflow Parameters
## See https://docs.elastiflow.com/docs/config_ref

## @skip config
config:
  EF_FLOW_ACCOUNT_ID: ""
  EF_FLOW_LICENSE_KEY: ""
  EF_FLOW_LICENSED_CORES: 1

  EF_FLOW_LOGGER_LEVEL: "info"
  EF_FLOW_LOGGER_ENCODING: "console"
  EF_FLOW_LOGGER_FILE_LOG_ENABLE: "false"
  EF_FLOW_LOGGER_FILE_LOG_FILENAME: "/var/log/elastiflow/flowcoll/flowcoll.log"
  EF_FLOW_LOGGER_FILE_LOG_MAX_SIZE: 100
  EF_FLOW_LOGGER_FILE_LOG_MAX_AGE: ""
  EF_FLOW_LOGGER_FILE_LOG_MAX_BACKUPS: 4
  EF_FLOW_LOGGER_FILE_LOG_COMPRESS: "false"

  EF_FLOW_SERVER_UDP_IP: "0.0.0.0"
  EF_FLOW_SERVER_UDP_PORT: 9995
  EF_FLOW_SERVER_UDP_PACKET_STREAM_MAX_SIZE: 4096
  EF_FLOW_SERVER_UDP_READ_BUFFER_MAX_SIZE: 

  EF_FLOW_DECODER_SETTINGS_PATH: "/etc/elastiflow"

  EF_FLOW_DECODER_IPFIX_ENABLE: "true"
  EF_FLOW_DECODER_NETFLOW1_ENABLE: "true"
  EF_FLOW_DECODER_NETFLOW5_ENABLE: "true"
  EF_FLOW_DECODER_NETFLOW6_ENABLE: "true"
  EF_FLOW_DECODER_NETFLOW7_ENABLE: "true"
  EF_FLOW_DECODER_NETFLOW9_ENABLE: "true"
  EF_FLOW_DECODER_SFLOW5_ENABLE: "true"
  EF_FLOW_DECODER_SFLOW_FLOWS_ENABLE: "true"
  EF_FLOW_DECODER_SFLOW_FLOWS_KEEP_SAMPLES: "false"
  EF_FLOW_DECODER_SFLOW_COUNTERS_ENABLE: "true"

  EF_FLOW_DECODER_TRANSLATE_KEEP_IDS: "default"

  EF_FLOW_DECODER_ENRICH_DNS_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_DNS_NAMESERVER_IP: ""
  EF_FLOW_DECODER_ENRICH_DNS_NAMESERVER_TIMEOUT: 3000
  EF_FLOW_DECODER_ENRICH_DNS_RESOLVE_PRIVATE: "true"
  EF_FLOW_DECODER_ENRICH_DNS_RESOLVE_PUBLIC: "true"
  EF_FLOW_DECODER_ENRICH_DNS_USERDEF_PATH: ""
  EF_FLOW_DECODER_ENRICH_DNS_USERDEF_REFRESH_RATE: 15
  EF_FLOW_DECODER_ENRICH_DNS_INCLEXCL_PATH: ""
  EF_FLOW_DECODER_ENRICH_DNS_INCLEXCL_REFRESH_RATE: 15

  EF_FLOW_DECODER_ENRICH_NETIF_GET_ATTRS: "true"
  EF_FLOW_DECODER_ENRICH_NETIF_CACHE_SIZE: 

  EF_FLOW_DECODER_ENRICH_SNMP_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_SNMP_PORT: 161
  EF_FLOW_DECODER_ENRICH_SNMP_VERSION: 2
  EF_FLOW_DECODER_ENRICH_SNMP_COMMUNITY: "public"
  EF_FLOW_DECODER_ENRICH_SNMP_TIMEOUT: 2
  EF_FLOW_DECODER_ENRICH_SNMP_RETRIES: 1

  EF_FLOW_DECODER_ENRICH_APP_CACHE_SIZE: 
  
  EF_FLOW_DECODER_ENRICH_APP_USERDEF_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_APP_USERDEF_PRIVATE: "true"
  EF_FLOW_DECODER_ENRICH_APP_USERDEF_PUBLIC: "true"
  EF_FLOW_DECODER_ENRICH_APP_USERDEF_PATH: "settings/apps_user_defined.yml"

  EF_FLOW_DECODER_ENRICH_ASN_PREF: "lookup"

  EF_FLOW_DECODER_ENRICH_RISKIQ_ASN_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_RISKIQ_ASN_ENDPOINT: "https://api.passivetotal.org/v2/netflow/as/download"
  EF_FLOW_DECODER_ENRICH_RISKIQ_ASN_REFRESH_INTERVAL: 1440
  EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_ENDPOINT: "https://api.passivetotal.org/v2/netflow/blocklist/download"
  EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_REFRESH_INTERVAL: 1440
  EF_FLOW_DECODER_ENRICH_RISKIQ_API_USER: ""
  EF_FLOW_DECODER_ENRICH_RISKIQ_API_KEY: ""
  EF_FLOW_DECODER_ENRICH_RISKIQ_API_TIMEOUT: 30
  EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_INCLEXCL_PATH: ""
  EF_FLOW_DECODER_ENRICH_RISKIQ_THREAT_INCLEXCL_REFRESH_RATE: 15

  EF_FLOW_DECODER_ENRICH_MAXMIND_ASN_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_MAXMIND_ASN_PATH: "maxmind/GeoLite2-ASN.mmdb"

  EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_PATH: "maxmind/GeoLite2-City.mmdb"
  EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_VALUES: "city,country,country_code,location,timezone"
  EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_LANG: "en"
  EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_INCLEXCL_PATH: ""
  EF_FLOW_DECODER_ENRICH_MAXMIND_GEOIP_INCLEXCL_REFRESH_RATE: 15

  EF_FLOW_DECODER_ENRICH_SAMPLERATE_CACHE_SIZE: 
  EF_FLOW_DECODER_ENRICH_SAMPLERATE_USERDEF_ENABLE: "false"
  EF_FLOW_DECODER_ENRICH_SAMPLERATE_USERDEF_PATH: "settings/sample_rate.yml"

  EF_FLOW_DECODER_ENRICH_COMMUNITYID_ENABLE: "true"
  EF_FLOW_DECODER_ENRICH_COMMUNITYID_SEED: 0
  EF_FLOW_DECODER_ENRICH_CONVERSATIONID_ENABLE: "true"
  EF_FLOW_DECODER_ENRICH_CONVERSATIONID_SEED: 0

  EF_FLOW_DECODER_ENRICH_JOIN_ASN: "true"
  EF_FLOW_DECODER_ENRICH_JOIN_GEOIP: "true"
  EF_FLOW_DECODER_ENRICH_JOIN_SEC: "true"
  EF_FLOW_DECODER_ENRICH_JOIN_NETATTR: "true"

  EF_FLOW_DECODER_DURATION_PRECISION: "ms"
  EF_FLOW_DECODER_TIMESTAMP_PRECISION: "ms"
  EF_FLOW_DECODER_PERCENT_NORM: 100
  EF_FLOW_DECODER_ENRICH_EXPAND_CLISRV: "true"
  EF_FLOW_DECODER_ENRICH_KEEP_CPU_TICKS: "false"

  EF_FLOW_RECORD_STREAM_MAX_SIZE: 

  # stdout
  EF_FLOW_OUTPUT_STDOUT_ENABLE: "false"
  EF_FLOW_OUTPUT_STDOUT_FORMAT: "json_pretty"

  # monitor
  EF_FLOW_OUTPUT_MONITOR_ENABLE: "false"
  EF_FLOW_OUTPUT_MONITOR_INTERVAL: 300

  # Elasticsearch
  EF_FLOW_OUTPUT_ELASTICSEARCH_ENABLE: "false"
  EF_FLOW_OUTPUT_ELASTICSEARCH_ECS_ENABLE: "false"
  EF_FLOW_OUTPUT_ELASTICSEARCH_BATCH_DEADLINE: 2000
  EF_FLOW_OUTPUT_ELASTICSEARCH_BATCH_MAX_BYTES: 
  EF_FLOW_OUTPUT_ELASTICSEARCH_TIMESTAMP_SOURCE: "end"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_PERIOD: "daily"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_SUFFIX: ""

  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_ENABLE: "true"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_OVERWRITE: "true"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_SHARDS: 1
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_REPLICAS: 0
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_REFRESH_INTERVAL: "10s"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_CODEC: "best_compression"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_ILM_LIFECYCLE: ""
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_ILM_ROLLOVER_ALIAS: ""
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_ISM_POLICY: ""
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_PIPELINE_DEFAULT: "_none"
  EF_FLOW_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_PIPELINE_FINAL: "_none"

  # A comma separated list of Elasticsearch nodes to use. DO NOT include "http://" or "https://"
  EF_FLOW_OUTPUT_ELASTICSEARCH_ADDRESSES: "127.0.0.1:9200"
  EF_FLOW_OUTPUT_ELASTICSEARCH_USERNAME: "elastic"
  EF_FLOW_OUTPUT_ELASTICSEARCH_PASSWORD: "changeme"
  EF_FLOW_OUTPUT_ELASTICSEARCH_CLOUD_ID: ""
  EF_FLOW_OUTPUT_ELASTICSEARCH_API_KEY: ""

  EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_ENABLE: "false"
  EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_SKIP_VERIFICATION: "false"
  EF_FLOW_OUTPUT_ELASTICSEARCH_TLS_CA_CERT_FILEPATH: ""

  EF_FLOW_OUTPUT_ELASTICSEARCH_RETRY_ENABLE: "true"
  EF_FLOW_OUTPUT_ELASTICSEARCH_RETRY_ON_TIMEOUT_ENABLE: "true"
  EF_FLOW_OUTPUT_ELASTICSEARCH_MAX_RETRIES: 3
  EF_FLOW_OUTPUT_ELASTICSEARCH_RETRY_BACKOFF: 1000

  # Splunk
  EF_FLOW_OUTPUT_SPLUNK_HEC_ENABLE: "false"
  EF_FLOW_OUTPUT_SPLUNK_HEC_HOST: ""
  EF_FLOW_OUTPUT_SPLUNK_HEC_PORT: 8088
  EF_FLOW_OUTPUT_SPLUNK_HEC_TOKEN: ""
  EF_FLOW_OUTPUT_SPLUNK_HEC_MAX_BYTES: 
  EF_FLOW_OUTPUT_SPLUNK_HEC_BATCH_DEADLINE: 2000
  EF_FLOW_OUTPUT_SPLUNK_HEC_TLS_ENABLE: true

  # Logz.io
  EF_FLOW_OUTPUT_LOGZIO_ENABLE: "false"
  EF_FLOW_OUTPUT_LOGZIO_HOST: "listener.logz.io"
  EF_FLOW_OUTPUT_LOGZIO_TOKEN: ""
  EF_FLOW_OUTPUT_LOGZIO_TIMESTAMP_SOURCE: "end"
  EF_FLOW_OUTPUT_LOGZIO_BATCH_DEADLINE: 2000
  EF_FLOW_OUTPUT_LOGZIO_BATCH_MAX_BYTES: 
  EF_FLOW_OUTPUT_LOGZIO_ECS_ENABLE: "false"
  EF_FLOW_OUTPUT_LOGZIO_TIMEOUT: 30000
  EF_FLOW_OUTPUT_LOGZIO_TLS_ENABLE: "false"

  # Kafka
  EF_FLOW_OUTPUT_KAFKA_ENABLE: "false"
  EF_FLOW_OUTPUT_KAFKA_BROKERS: ""
  EF_FLOW_OUTPUT_KAFKA_VERSION: "1.0.0"
  EF_FLOW_OUTPUT_KAFKA_CLIENT_ID: "elastiflow-flowcoll"
  EF_FLOW_OUTPUT_KAFKA_RACK_ID: ""
  EF_FLOW_OUTPUT_KAFKA_TIMEOUT: 30

  EF_FLOW_OUTPUT_KAFKA_SASL_ENABLE: "false"
  EF_FLOW_OUTPUT_KAFKA_SASL_USERNAME: ""
  EF_FLOW_OUTPUT_KAFKA_SASL_PASSWORD: ""

  EF_FLOW_OUTPUT_KAFKA_TLS_ENABLE: "false"
  EF_FLOW_OUTPUT_KAFKA_TLS_CA_CERT_FILEPATH: ""
  EF_FLOW_OUTPUT_KAFKA_TLS_CERT_FILEPATH: ""
  EF_FLOW_OUTPUT_KAFKA_TLS_KEY_FILEPATH: ""
  EF_FLOW_OUTPUT_KAFKA_TLS_SKIP_VERIFICATION: "false"

  EF_FLOW_OUTPUT_KAFKA_PRODUCER_MAX_MESSAGE_BYTES: 
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_REQUIRED_ACKS: 1
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_TIMEOUT: 10
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_COMPRESSION: 0
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_COMPRESSION_LEVEL: -1000
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_FLUSH_BYTES: 
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_FLUSH_MESSAGES: 1024
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_FLUSH_FREQUENCY: 500
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_FLUSH_MAX_MESSAGES: 0
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_RETRY_MAX: 3
  EF_FLOW_OUTPUT_KAFKA_PRODUCER_RETRY_BACKOFF: 100
  
  # RiskIQ
  EF_FLOW_OUTPUT_RISKIQ_ENABLE: "false"
  EF_FLOW_OUTPUT_RISKIQ_HOST: ""
  EF_FLOW_OUTPUT_RISKIQ_PORT: 
  EF_FLOW_OUTPUT_RISKIQ_CUSTOMER_UUID: ""
  EF_FLOW_OUTPUT_RISKIQ_CUSTOMER_ENCRYPTION_KEY: ""

##
## official elastiflow image
## @param image.registry elastiflow image registry
## @param image.repository elastiflow image repository
## @param image.tag elastiflow image tag (immutable tags are recommended)
## @param image.pullPolicy elastiflow image pull policy
## @param image.pullSecrets elastiflow image pull secrets
##
image:
  registry: docker.io
  repository: elastiflow/flow-collector
  tag: 5.3.5
  ## Specify a imagePullPolicy
  ## Defaults to "Always" if image tag is "latest", else set to "IfNotPresent"
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []

## @param replicaCount Number of elastiflow replicas to deploy
##
replicaCount: 1
## @param containerPorts.elastiflow elastiflow port
##
containerPorts:
  elastiflow: 9995
## @param customLivenessProbe Custom livenessProbe that overrides the default one
##
customLivenessProbe: {}
## @param customReadinessProbe Custom readinessProbe that overrides the default one
##
customReadinessProbe: {}
## @param customStartupProbe Custom startupProbe that overrides the default one
##
customStartupProbe: {}
## elastiflow resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits The resources limits for the elastiflow containers
## @param resources.requests The requested resources for the elastiflow containers
##
resources:
  limits: {}
  requests: {}

## @param existingConfigmap The name of an existing ConfigMap with your custom configuration for elastiflow
##
existingConfigmap:
## @param command Override default container command (useful when using custom images)
##
command: []
## @param args Override default container args (useful when using custom images)
##
args: []
## @param hostAliases elastiflow pods host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []
## @param podLabels Extra labels for elastiflow pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}
## @param podAnnotations Annotations for elastiflow pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}
## @param podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAffinityPreset: ""
## @param podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft
## Node affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  ## @param nodeAffinityPreset.type Node affinity preset type. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ##
  type: ""
  ## @param nodeAffinityPreset.key Node label key to match. Ignored if `affinity` is set
  ##
  key: ""
  ## @param nodeAffinityPreset.values Node label values to match. Ignored if `affinity` is set
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []
## @param affinity Affinity for elastiflow pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## NOTE: `podAffinityPreset`, `podAntiAffinityPreset`, and `nodeAffinityPreset` will be ignored when it"s set
##
affinity: {}
## @param nodeSelector Node labels for elastiflow pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## @param tolerations Tolerations for elastiflow pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## @param updateStrategy.type elastiflow statefulset strategy type
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
##
updateStrategy:
  ## StrategyType
  ## Can be set to RollingUpdate or OnDelete
  ##
  type: RollingUpdate
## @param priorityClassName elastiflow pods" priorityClassName
##
priorityClassName: ""
## @param schedulerName Name of the k8s scheduler (other than default) for elastiflow pods
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ""
## @param lifecycleHooks for the elastiflow container(s) to automate configuration before or after startup
##
lifecycleHooks: {}
## @param extraEnvVars Array with extra environment variables to add to elastiflow nodes
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for elastiflow nodes
##
extraEnvVarsCM:
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for elastiflow nodes
##
extraEnvVarsSecret:
## @param extraVolumes Optionally specify extra list of additional volumes for the elastiflow pod(s)
##
extraVolumes: []
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for the elastiflow container(s)
##
extraVolumeMounts: []
## @param sidecars Add additional sidecar containers to the elastiflow pod(s)
## e.g:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: {}
## @param initContainers Add additional init containers to the elastiflow pod(s)
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ["sh", "-c", "echo "hello world""]
##
initContainers: {}

service:
  ## @param service.type elastiflow service type
  ##
  type: ClusterIP
  ## @param service.ports.elastiflow elastiflow service UDP port
  ##
  ports:
    elastiflow: 9995
  ## Node ports to expose
  ## @param service.nodePorts.http Node port for HTTP
  ## @param service.nodePorts.https Node port for HTTPS
  ## NOTE: choose port between <30000-32767>
  ##
  nodePorts:
    http:
    https:
  ## @param service.clusterIP elastiflow service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  clusterIP:
  ## @param service.loadBalancerIP elastiflow service Load Balancer IP
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
  ##
  loadBalancerIP:
  ## @param service.loadBalancerSourceRanges elastiflow service Load Balancer sources
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## e.g:
  ## loadBalancerSourceRanges:
  ##   - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
  ## @param service.externalTrafficPolicy elastiflow service external traffic policy
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## @param service.annotations Additional custom annotations for elastiflow service
  ##
  annotations: {}
  ## @param service.extraPorts Extra ports to expose in elastiflow service (normally used with the `sidecars` value)
  ##
  extraPorts: []

## @section Other Parameters

## RBAC configuration
##
rbac:
  ## @param rbac.create Specifies whether RBAC resources should be created
  ##
  create: false

## ServiceAccount configuration
##
serviceAccount:
  ## @param serviceAccount.create Specifies whether a ServiceAccount should be created
  ##
  create: false
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the common.names.fullname template
  ##
  name: ""
